name: tests

on: [push, pull_request]

env:
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        node: ['lts/*']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm i
    - run: npm test
      env:
        NEOCITIES_API_TOKEN: ${{ secrets.NEOCITIES_API_TOKEN }}

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.head_ref, 'dependabot/github_actions') }}
        with:
          github-token: ${{secrets.github_token}}
